### PR TITLE
Themes option added to the menu

### PR DESCRIPTION
**Pull request by cljones**
The theme option with default and dark theme was added to the Airviewer2 menu.  The colors still need to be implemented.

### CODE REVIEW

**Comment by anitaoranusi** [comment]
Is there code for the theme options? Because it just shows your commit message and not any code for the options if there was any.

**Comment by cljones** [comment]
@anitaoranusi There is fxml code for the theme option.  If you click on the title of my commit it should show you.

**Comment by pabitraale** [comment]
Is it possible to see before and after screen shot.

**Comment by cljones** [comment]
> Is it possible to see before and after screen shot.

I am not sure if there is a way to do that.

**Comment by cljones** [comment]
@pabitraale I am not sure if there is a way to do that.

**Comment by anitaoranusi** [comment]
@pabitraale So, the green part is what he added to the file. Everything else that's not green (the white) is what was left unchanged. If he had deleted something, whatever he deleted would be in red

**Comment by anitaoranusi** [comment]
> @anitaoranusi There is fxml code for the theme option. If you click on the title of my commit it should show you.

Ah ok, that's my bad. It looks pretty good to me. The code explains itself and doesn't look overly complicated

**Pull request merged**
